CREATE TABLE survey (
    userID INTEGER PRIMARY KEY AUTOINCREMENT,
    pairID INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    q1 TEXT NOT NULL,
    q2 TEXT NOT NULL,
    q3 TEXT NOT NULL,
    q4 TEXT NOT NULL,
    q5 TEXT NOT NULL,
    q6 TEXT NOT NULL,
    q7 TEXT NOT NULL,
);

CREATE TABLE TikToks (
    videoID INTEGER PRIMARY KEY,
    category TEXT,
    
)

